name: 'Lock Threads'

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: lock

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-inactive-days: "2"
          exclude-any-issue-labels: "discussion"
          issue-comment: "This issue is locked to prevent necro-posting on closed issues. Please create a new issue for related bugs."
          issue-lock-reason: ""
          pr-inactive-days: "7"
          pr-comment: "This issue is locked to prevent necro-posting on closed issues. Please create a new issue for related discussion, if needed."
          pr-lock-reason: ""
